export const YEUTHICH_LIST_REQUEST = 'YEUTHICH_LIST_REQUEST';
export const YEUTHICH_LIST_SUCCESS = 'YEUTHICH_LIST_SUCCESS';
export const YEUTHICH_LIST_FAIL = 'YEUTHICH_LIST_FAIL';

export const YEUTHICH_CREATE_REQUEST = 'YEUTHICH_CREATE_REQUEST';
export const YEUTHICH_CREATE_SUCCESS = 'YEUTHICH_CREATE_SUCCESS';
export const YEUTHICH_CREATE_FAIL = 'YEUTHICH_CREATE_FAIL';
export const YEUTHICH_CREATE_RESET = 'YEUTHICH_CREATE_RESET';

export const YEUTHICH_DELETE_REQUEST = 'YEUTHICH_DELETE_REQUEST';
export const YEUTHICH_DELETE_SUCCESS = 'YEUTHICH_DELETE_SUCCESS';
export const YEUTHICH_DELETE_FAIL = 'YEUTHICH_DELETE_FAIL';
export const YEUTHICH_DELETE_RESET = 'YEUTHICH_DELETE_RESET';